- name: install mariadb package (Rocky)
  tags: rocky,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"    
  
- name: install mariadb package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"